trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: FirstStage
  displayName: 'First Stage'
  jobs:
  - job: FirstStageJob
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- stage: FirstPipelineStage
  displayName: 'Trigger Third Pipeline'
  jobs:
  - job: FirstPipelineJob
    steps:
    - script: echo "Trigger Third Pipeline"
      displayName: 'Trigger Thrid Pipeline'
