trigger: none

parameters:
  - name: dockerImageName
    displayName: 'Docker image Name'
    type: 'string'
    default: 'mcr.microsoft.com/dotnet/aspnet'
  - name: dockerImageTag
    displayName: 'Docker image Tag'
    type: string
    default: '8.0'

stages:
- stage: TestDockerImage
  displayName: 'Test Docker Image'
  jobs:
  - job: PullAndRunDockerImage
    displayName: 'Pull and Run Docker Image'
    strategy:
      matrix:
        windows:
          vmImage: 'windows-latest'
        ubuntu:
          vmImage: 'ubuntu-latest'
    pool:
      vmImage: $(vmImage)
    steps:
    - script: |
        docker pull ${{ parameters.dockerImageName }}:${{ parameters.dockerImageTag }}
        docker run --rm -d -p 8080:80 --name testContainer ${{ parameters.dockerImageName }}:${{ parameters.dockerImageTag }}
        docker ps
      displayName: 'Pull and run Docker image'
    - script: |
        docker stop testContainer
      displayName: 'Stop Docker container'
      condition: always()