trigger:
- main

parameters:
  - name: dockerImage
    displayName: 'Docker image name'
    type: string
    default: 'mcr.microsoft.com/dotnet/aspnet:8.0'

stages:
- stage: TestDockerImage
  displayName: 'Test Docker Image'
  jobs:
  - job: PullAndRunDockerImage
    displayName: 'Pull and Run Docker Image'
    strategy:
      matrix:
        windows:
          vmImage: 'windows-latest'
        ubuntu:
          vmImage: 'ubuntu-latest'
        mac:
          vmImage: 'macOS-latest'
    pool:
      vmImage: $(vmImage)
    steps:
    - script: |
        docker pull ${{ parameters.dockerImage }}
        docker run --rm -d -p 8080:80 --name testContainer ${{ parameters.dockerImage }}
        docker ps
      displayName: 'Pull and run Docker image'
    - script: |
        docker stop testContainer
      displayName: 'Stop Docker container'
      condition: always()