trigger: none

resources:
  pipelines:
    - pipeline: firstPipeline
      source: 'first-pipeline'
      project: DevOpsTraining
      trigger: 
        stages:
        - FirstPipelineStage
    - pipeline: secondPipeline
      source: 'second-pipeline'
      project: DevOpsTraining
      trigger: 
        stages:
        - SecondPipelineStage

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- ${{ if eq(variables['Build.Reason'], 'ResourceTrigger')}}:
  - script: echo The pipeline was triggered by $(resources.triggeringAlias)
  - ${{ if eq(variables['resources.triggeringAlias'], 'firstPipeline') }}:
    - script: echo "First Pipeline triggered this run with conditional insertion."
  - ${{ if eq(variables['resources.triggeringAlias'], 'secondPipeline') }}:
    - script: echo "Second Pipeline triggered this run with conditional insertion."
  - script: echo "First Pipeline triggered this run with condition."
    condition: and(succeeded(), eq(variables['resources.triggeringAlias'], 'firstPipeline'))
  - script: echo "Second Pipeline triggered this run with condition."
    condition: and(succeeded(), eq(variables['resources.triggeringAlias'], 'secondPipeline'))
- ${{ else }}:
  - script: echo Not trigger by `ResourceTrigger`
