trigger: none

resources:
  pipelines:
    - pipeline: firstPipeline
      source: 'first-pipeline'
      project: DevOpsTraining
      trigger: 
        stages:
        - FirstPipelineStage
    - pipeline: secondPipeline
      source: 'second-pipeline'
      project: DevOpsTraining
      trigger: 
        stages:
        - SecondPipelineStage

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- ${{ if eq(variables['Build.Reason'], 'ResourceTrigger')}}:
  - script: echo "resources.triggeringAlias is firstPipeline"
    condition: and(succeeded(), eq(variables['resources.triggeringAlias'], 'firstPipeline'))
  - script: echo "resources.triggeringAlias is secondPipeline"
    condition: and(succeeded(), eq(variables['resources.triggeringAlias'], 'secondPipeline'))
  - script: echo "resources.pipeline.firstPipeline.triggered is true"
    condition: and(succeeded(), , eq(variables['resources.pipeline.firstPipeline.triggered'], 'true'))
  - script: echo "resources.pipeline.secondPipeline.triggered is true"
    condition: and(succeeded(), , eq(variables['resources.pipeline.secondPipeline.triggered'], 'true'))
- ${{ else }}:
  - script: echo Not trigger by `ResourceTrigger`
